

services:
  dnpm-etl-processor:
    image: ghcr.io/ccc-mf/etl-processor:latest
    environment:
      LOGGING_LEVEL_DEV: ${DNPM_LOG_LEVEL:-INFO}
      SPRING_KAFKA_SECURITY_PROTOCOL: ${DNPM_KAFKA_SECURITY_PROTOCOL:-SSL}
      SPRING_KAFKA_SSL_TRUST-STORE-TYPE: PKCS12
      SPRING_KAFKA_SSL_TRUST-STORE-LOCATION: /opt/dnpm-processor/ssl/truststore.jks
      SPRING_KAFKA_SSL_TRUST-STORE-PASSWORD: ${KAFKA_TRUST_STORE_PASSWORD}
      SPRING_KAFKA_SSL_KEY-STORE-TYPE: PKCS12
      SPRING_KAFKA_SSL_KEY-STORE-LOCATION: /opt/dnpm-processor/ssl/keystore.jks
      SPRING_KAFKA_SSL_KEY-STORE-PASSWORD: ${DNPM_PROCESSOR_KEY_STORE_PASSWORD}
      SPRING_KAFKA_PRODUCER_COMPRESSION-TYPE: gzip
      APP_KAFKA_TOPIC: ${DNPM_KAFKA_TOPIC}
      APP_KAFKA_SERVERS: ${KAFKA_BROKERS}
      APP_KAFKA_GROUP_ID: ${DNPM_KAFKA_GROUP_ID}
      APP_KAFKA_RESPONSE_TOPIC: ${DNPM_KAFKA_RESPONSE_TOPIC}
      APP_REST_URI: ${DNPM_BWHC_REST_URI}
      APP_REST_USERNAME: ${DNPM_BWHC_REST_USERNAME}
      APP_REST_PASSWORD: ${DNPM_BWHC_REST_PASSWORD}
      APP_REST_IS_BWHC: ${DNPM_BWHC_REST_IS_BWHC}
      APP_SECURITY_ADMIN_USER: ${DNPM_ADMIN_USER}
      APP_SECURITY_ADMIN_PASSWORD: ${DNPM_ADMIN_PASSWORD}
      SPRING_DATASOURCE_URL: ${DNPM_DATASOURCE_URL}
      SPRING_DATASOURCE_PASSWORD: ${DNPM_MARIADB_USER_PW}
      SPRING_DATASOURCE_USERNAME: ${DNPM_MARIADB_DB}
      APP_PSEUDONYMIZE_GPAS_SSLCALOCATION: /workspace/opt/dnpm-processor/ssl/mosaic.crt
      APP_PSEUDONYMIZE_GPAS_PASSWORD: ${DNPM_PSEUDONYMIZE_GPAS_PASSWORD}
      APP_PSEUDONYMIZE_GPAS_USERNAME: ${DNPM_PSEUDONYMIZE_GPAS_USERNAME}
      APP_PSEUDONYMIZE_GPAS_TARGET: ${DNPM_PSEUDONYMIZE_GPAS_TARGET}
      APP_PSEUDONYMIZE_GPAS_URI: ${DNPM_PSEUDONYMIZE_GPAS_URI}
      APP_PSEUDONYMIZE_PREFIX: ${DNPM_APP_PSEUDONYMIZE_PREFIX}
      APP_PSEUDONYMIZER: ${DNPM_PSEUDONYMIZE_GENERATOR}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      #- ${DNPM_TO_SSL_KEYSTORE_LOCATION}:/workspace/opt/dnpm-processor/ssl/keystore.jks:ro
      #- ${KAFKA_TRUST_STORE_LOCATION}:/workspace/opt/dnpm-processor/ssl/truststore.jks:ro
      #- ${DNPM_PSEUDONYMIZE_GPAS_SSLCALOCATION}:/workspace/opt/dnpm-processor/ssl/mosaic.crt

    depends_on:
      - dnpm-monitor-db
    ports:
      - "${DNPM_MONITORING_HTTP_PORT:-8080}:8080"

  # todo add volume
  dnpm-monitor-db:
    image: mariadb:10
    environment:
      MARIADB_DATABASE: ${DNPM_MARIADB_DB}
      MARIADB_USER: ${DNPM_MARIADB_USER}
      MARIADB_PASSWORD: ${DNPM_MARIADB_USER_PW}
      MARIADB_ROOT_PASSWORD: ${DNPM_MARIADB_ROOT_PW}
    expose:
      - "3306"



